version: '{build}'
configuration: Release
platform: x64
image:
- Visual Studio 2017
clone_folder: c:\projects\lc0
install:
- cmd: set PATH=C:\Python38;C:\Python38\scripts;%PATH%
- cmd: pip3 install --upgrade meson
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
- cmd: cd C:\projects\lc0
cache:
  - C:\projects\lc0\subprojects\packagecache
before_build:
- cmd: git submodule update --init --recursive
- cmd: meson build --backend vs2017 --buildtype release -Dbuild_backends=false -Dgtest=false -Ddefault_library=static
build_script:
- cmd: cd build
- cmd: msbuild "C:\projects\lc0\build\rescorer.sln" /m /p:WholeProgramOptimization=true /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: cd C:\projects\lc0
artifacts:
  - path: build/rescorer.exe
    name: rescorer
